#!/bin/bash
# NyxOS Quick Start Guide

echo "╔════════════════════════════════════════════════╗"
echo "║  NyxOS v1-STABLE - Quick Start                 ║"
echo "╚════════════════════════════════════════════════╝"
echo ""
echo "📋 Prerequisites:"
echo "  1. i686-elf-gcc cross-compiler"
echo "     sudo apt-get install gcc-i686-linux-gnu binutils-i686-linux-gnu"
echo ""
echo "  2. GRUB tools & xorriso"
echo "     sudo apt-get install grub-pc xorriso"
echo ""
echo "  3. QEMU (for testing)"
echo "     sudo apt-get install qemu-system-x86"
echo ""
echo "🔨 Build Steps:"
echo "  cd /workspaces/NYXOS"
echo "  make clean"
echo "  make              # Build kernel ELF"
echo "  make iso          # Create bootable ISO"
echo ""
echo "▶️  Run in QEMU:"
echo "  make run"
echo "  # or manually:"
echo "  qemu-system-i386 -cdrom build/nyxos.iso -m 256M"
echo ""
echo "📁 Project Structure:"
echo "  kernel/         - Core OS components"
echo "  kernel/arch/x86 - x86 assembly & protected mode"
echo "  kernel/cpu      - CPU detection (CPUID)"
echo "  kernel/drivers  - Screen, keyboard, timer"
echo "  kernel/mm       - Memory management & malloc/free"
echo "  kernel/fs       - Virtual filesystem"
echo "  kernel/sched    - Task scheduler"
echo "  shell/          - Command-line shell"
echo "  apps/           - Built-in commands"
echo "  lib/            - String utilities"
echo ""
echo "🐚 Shell Commands:"
echo "  help       - Show command list"
echo "  echo TEXT  - Print text"
echo "  clear      - Clear screen"
echo "  osinfo     - Show OS & CPU info"
echo "  version    - Show version"
echo "  ls         - List files"
echo "  cat <file> - Display file"
echo "  meminfo    - Show memory stats"
echo "  shutdown   - Halt system"
echo ""
echo "📚 Documentation:"
echo "  See README.md for full details"
echo ""
